
Competition.destroy_all 
Team.destroy_all 
# Competition seed data
c1 = Competition.create(name: "Premier League", plan: "TIER ONE", country: "England") 
c2 = Competition.create(name: "World Cup", plan: "TIER ONE", country: "World") 
c3 = Competition.create(name: "UEFA Champions League", plan: "TIER ONE", country: "Europe") 
c4 = Competition.create(name: "Serie A", plan: "TIER ONE", country: "Italy")
c5 = Competition.create(name: "La Liga", plan: "TIER ONE", country: "Spain")
c6 = Competition.create(name: "Serie A", plan: "TIER ONE", country: "Brazil") 
c7 = Competition.create(name: "Bundesliga", plan: "TIER ONE", country: "Germany")  
c8 = Competition.create(name: "Superliga Argentina", plan: "TIER TWO", country: "Germany")
c9 = Competition.create(name: "A League", plan: "TIER TWO", country: "Australia") 
c10 = Competition.create(name: "Jupiler Pro League", plan: "TIER TWO", country: "Belgium") 
c11 = Competition.create(name: "Major League Soccer", plan: "TIER TWO", country: "USA") 
c12 = Competition.create(name: "FA Cup", plan: "TIER TWO", country: "England") 
c13 = Competition.create(name: "J. League", plan: "TIER TWO", country: "Japan") 
c14 = Competition.create(name: "UEFA Europa League", plan: "TIER TWO", country: "Europe")        
c15 = Competition.create(name: "Bundesliga", plan: "TIER THREE", country: "Austria") 
c16 = Competition.create(name: "Primera Division", plan: "TIER THREE", country: "Chile") 
c17 = Competition.create(name: "Primera Division", plan: "TIER THREE", country: "Peru") 
c18 = Competition.create(name: "Superliga", plan: "TIER THREE", country: "Denmark") 
c19 = Competition.create(name: "Liga MX", plan: "TIER THREE", country: "Mexico") 
c20 = Competition.create(name: "Coppa Italia", plan: "TIER THREE", country: "Italy") 
c21 = Competition.create(name: "Serie B", plan: "TIER THREE", country: "Brazil") 
c22 = Competition.create(name: "Serie C", plan: "TIER FOUR", country: "Brazil") 
c23 = Competition.create(name: "Supercopa Argentina", plan: "TIER FOUR", country: "Argentina") 
c24 = Competition.create(name: "Canadian Championship", plan: "TIER FOUR", country: "Canada") 
c25 = Competition.create(name: "I- League", plan: "TIER FOUR", country: "India") 
c26 = Competition.create(name: "Serie C", plan: "TIER FOUR", country: "Italy")
c27 = Competition.create(name: "National League", plan: "TIER FOUR", country: "England") 
c28 = Competition.create(name: "ABSA Premiership", plan: "TIER FOUR", country: "South Africa")       
# Team seed data 
t1 = Team.create(name: "Argentina", short_name: "ARG", last_updated: DateTime.now, venue: "Estadio Alberto José Armando") 
t2 = Team.create(name: "Uruguay", short_name: "URY", last_updated: DateTime.now, venue: "Guangxi Sports Centre Stadium") 
t3 = Team.create(name: "Brazil", short_name: "BRA", last_updated: DateTime.now, venue: "Anfield") 
t4 = Team.create(name: "Japan", short_name: "JPN", last_updated: DateTime.now, venue: "Stade Maurice Dufrasne") 
t5 = Team.create(name: "Mexico", short_name: "MEX", last_updated: DateTime.now, venue: "Levi's Stadium") 
t6 = Team.create(name: "Korea Republic", short_name: "KOR", last_updated: DateTime.now, venue: "Jeonju World Cup Stadium") 
t7 = Team.create(name: "Nigeria", short_name: "NIG", last_updated: DateTime.now, venue: "Rudolf-Tonn-Stadion") 
t8 = Team.create(name: "Australia", short_name: "AUS", last_updated: DateTime.now, venue: "NV Arena") 
t9 = Team.create(name: "Serbia", short_name: "SER", last_updated: DateTime.now, venue: "Merkur Arena")   
